docs(update-version-control): update Version Control Section
pondevelopment/restful-api-guidelines pull request #34
Opened 2022-09-08 06:43 UTC by pon-james

Add that all code that falls under intellectual property must be stored in the Github Enterprise account.

2022-10-17 13:32 UTC, zeger-pon requested changes

2022-10-17 13:32 UTC, zeger-pon commented on chapters/development/version-control.adoc
> +All code that is intellectual property must be stored in the enterprise account. Use of personal accounts for the purpose of storing and versioning code that is intellectual property is not permitted
All code commissioned code is intellectual property and must be stored in a Pon-managed source code repository. Preferably in the Pon maintained Github environment.

Rephrase forbidden to "strictly prohibited"?

2022-11-14 18:48 UTC, pon-james commented on chapters/development/version-control.adoc
> +All code that is intellectual property must be stored in the enterprise account. Use of personal accounts for the purpose of storing and versioning code that is intellectual property is not permitted
@zeger-pon addressed in c5c61b0fba53df07ac2e589109f5e722c4e7f2f5

2023-03-14 07:58 UTC, zeger-pon requested changes

2023-03-14 07:58 UTC, zeger-pon commented on chapters/development/version-control.adoc
> +All commissioned code is intellectual property and must be stored in a Pon-managed source code repository. Preferably in the Pon maintained Github environment. Use of personal accounts for the purpos
All commissioned code is intellectual property and must be stored in a Pon-managed source code repository, preferably in the Pon-maintained Github environment. Use of personal accounts to store and version code that is intellectual property is strictly prohibited.

2023-05-26 11:08 UTC, pon-james commented on chapters/development/version-control.adoc
> +All commissioned code is intellectual property and must be stored in a Pon-managed source code repository. Preferably in the Pon maintained Github environment. Use of personal accounts for the purpos
@zeger-pon addressed in https://github.com/pondevelopment/restful-api-guidelines/pull/34/commits/95d3323e5d390bbff114d828d827b46519bce519

2024-02-22 11:24 UTC, merged